#
# dns-admin.yaml : MikroTik management tools
#
# Copyright (c) 2025 Tim Hosking
# Website: https://github.com/munger
# Licence: MIT
#

# DNS management group

group:
  name: dns-admin
  description: "DNS management"
  modules: [dns]
  default_access: read-write
