#
# full-admin.yaml : MikroTik management tools
#
# Copyright (c) 2025 Tim Hosking
# Website: https://github.com/munger
# Licence: MIT
#

# Full administrative access group

group:
  name: full-admin
  description: "Full administrative access to all modules"
  modules: "*"
  default_access: read-write
