#
# monitor.yaml : MikroTik management tools
#
# Copyright (c) 2025 Tim Hosking
# Website: https://github.com/munger
# Licence: MIT
#

# Monitoring group (read-only)

group:
  name: monitor
  description: "Read-only monitoring"
  modules: [resources, logs, netwatch, torch, health, watchdog, sniffer, graphing]
  default_access: read
